name: Roles Royce tests

on: [push]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run tests
        run: |
          pip install -r requirements-dev.txt
          pytest -v --cov
      - name: Coverage report
        run: coverage report
